
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  # app user (non-root)
  DB_USERNAME: YXBwdXNlcg==       
  # app password (taken from .env DB_PASSWORD)
  DB_PASSWORD: cm9vdHBhc3N3b3Jk    
  # root password for initial MySQL setup (from .env MYSQL_ROOT_PASSWORD)
  DB_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk  
  # Base64 for "some-long-and-secure-jwt-secret-key-12345678"
  JWT_SECRET: c29tZS1sb25nLWFuZC1zZWN1cmUtand0LXNlY3JldC1rZXktMTIzNDU2Nzg=
