apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend-sa
      containers:
      - name: backend
        # Using Cloud Build pushed image in Artifact Registry
        image: europe-west3-docker.pkg.dev/resellplatform/backend/backend:1a69eaf
        # Force pulling latest image when pods are recreated so config / build changes take effect
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_APPLICATION_NAME
          value: backend

        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/resell

        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update

        - name: SPRING_JPA_SHOW_SQL
          value: "true"

        - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
          value: org.hibernate.dialect.MySQLDialect

        # FROM SECRET
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: DB_USERNAME

        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: DB_PASSWORD
        startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
        readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
        livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"  # 0.2 CPU
          limits:
            memory: "1000Mi"
            cpu: "1000m"  # 1.0 CPU      
        

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer # Changed to LoadBalancer for easier testing if you want to hit API directly, otherwise ClusterIP
