apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  annotations:
    # This connects the K8s Service Account to the GCP Service Account
    # Replace <PROJECT_ID> with your actual project ID
    iam.gke.io/gcp-service-account: storage-uploader@resellplatform.iam.gserviceaccount.com
